### ISSUE TITLE
Que le paso a Captureflag.io

### ISSUE THREAD

**Issue by SAYSARA** [LuisMuz/captureFlag#1]
Hola, soy SAYSARA espero que leas este mensaje. He jugado su juego Captureflag.io y me he dado cuenta de que en ninguna página WEB funciona yo jugaba este juego antes y pues lo he estado buscando por mucho tiempo que le paso al juego hubo un hackeo ¿tiene problemas de compatibilidad? Tengo un Windows 10 sabe. Quiero saber que el juego sigue existiendo y es jugable, lo bueno es que aún no es Lost Media y por eso estoy preguntando sé que ha subido código, pero como se ejecuta?. Gracias por leer

**Comment by LuisMuz** [comment]
Hola, sobre el sitio web no tengo conocimiento de lo que le haya pasado, este ejercicio lo hice para una materia de la uni, y si estuvo bastante divertido.

- Para ver si teniamos las respuestas bien, tuvimos que checar las flags en la pagina de [challenges reply](https://challenges.reply.com/) y el link directo para checar ese contest fue [este](https://challenges.reply.com/tamtamy/challenge/reply-cybersecurity-challenge-2022/detail)

- Para ejecutarlo solo tienes que compilar cada lenguaje en su respectivo compilador y darle la entrada del problema
